# Page settings

baseurl = "https://resume.grantjoseph.me/"
languageCode = "en-us"
title = "Grant Joseph Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Grant Joseph"
        tagline = "Systems Engineer"
        avatar = ""

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: grantj1788@gmail.com"
        title = "grantj1788@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:217.370.9684"
        title = "217.370.9684"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "https://grantjoseph.me/"
        title = "grantjoseph.me"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "https://www.linkedin.com/in/grant-joseph-35b359116/"
        title = "LinkedIn"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "https://github.com/SloppyTurtle"
        title = "Github"



    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        college = "Jacksonville High School"
        dates = "2003 - 2007"


    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"


    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "My Pets"

        [[params.interests.list]]
        interest = "Gaming"

        [[params.interests.list]]
        interest = "Cooking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "Responsible for designing, building, deploying, evaluating, and maintaining IT infrastructure using the latest technology to ensure reliability to all IT systems that support the business are efficient and seamless."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Systems Engineer"
        dates = "05/2022 - Present"
        company = "Central Laborers Pension Fund"
        details = "Windows/Linux systems administration and maintenance. **-** Installing and supporting system hardware and software, performing system upgrades and evaluating and installing patches and software updates. This also includes managing system alerts, triaging incidents, and reporting findings. **-** Supporting Central Laborers' security policies and activities for network, system and application vulnerability management and mitigation **-**  Administering and configuring DNS/DHCP/AD/VMWare/Network devices such as switches, routers, and wireless access points **-** •	Managing backup and recovery with Veeam"

        [[params.jobs.list]]
        position = "Information Systems Security Officer"
        dates = "10/2021 - 05/2022"
        company = "Alliance Community Bank"
        details = "I oversee the direction and operation of the technical infrastructure of the organization, management of projects, budgets, and vendor relationships **-** I am responsible for information security and IT risk management based on industry accepted frameworks **-** I manage our cyber security structure, policies and processes and I am the chair of our IT committee **-** I am a hands-on manager who is the primary technical-infrastructure and security expert in the company. This includes PC and network (LAN/WAN) support and planning, information security and VOIP system/voice communications **-** I also serve as the primary liaison with bank audit and regulatory examination teams to ensure the safe, secure, and compliant im- plementation of industry and bank regulatory policy requirements and regulations **-** Trained users via KnowBe4 and promoted security awareness to boost system security and improve server and network efficiency. **-** Monitored current ESET and SecureWorks reports for vulnerabilities **-** I managed patches, data backups and security changes"

        [[params.jobs.list]]
        position = "IT Manager"
        dates = "09/2020 - 10/2021"
        company = "JBS USA"
        details = "Managing and determining time frames for major information technology projects including system updates, upgrades, migrations and outages **-** Leading technical projects that include our electronic and automation teams **-** Managing and reporting on allocation of IT budget and purchasing **-** Support and manage all computer/network hardware at assigned location **-** Work with end users and propose new hardware and software solutions to support the business **-** Test all hardware, operating systems and software modifications before they are introduced into production **-** Provide hardware and software diagnostics for network, hardware and software issues **-** Overseeing technology projects in compliance with IT standards **-** Provide hardware and network support for “Production Floor” computer systems"

        [[params.jobs.list]]
        position = "IT Field Technician"
        dates = "04/2019 - 09/2020"
        company = "JBS USA"
        details = "Support and manage all computer/network hardware at assigned location **-** Work with end users and propose new hardware and software solutions to support the business **-** Test all hardware, operating systems and software modifications before they are introduced into production **-** Provide hardware and software diagnostics for network, hardware and software issues **-** Overseeing technology projects in compliance with IT standards **-** Provide hardware and network support for “Production Floor” computer systems."

        [[params.jobs.list]]
        position = "IT Support Technician"
        dates = "12/2016 - 04/2019"
        company = "Prairieland FS, Inc"
        details = "I provide technical support to all company locations including server management, implementation/installation of hardware, developing and maintaining standards for hardware and network usage, managing hardware and operating licensing/contracts and customer support for the employees."

        [[params.jobs.list]]
        position = "District Technicain"
        dates = "01/2015 - 12/2016"
        company = "Jacksonville School District"
        details = "I provide on-site computer support and hardware repair, trouble shooting of the technology used in the class rooms and regular maintenance of the electronics throughout the district."

    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Windows"
        level = "100%"
                
        [[params.skills.list]]
        skill = "Linux"
        level = "100%"

        [[params.skills.list]]
        skill = "Active Directory"
        level = "100%"

        [[params.skills.list]]
        skill = "SecureWorks IDS"
        level = "100%"

        [[params.skills.list]]
        skill = "ESET"
        level = "100%"

        [[params.skills.list]]
        skill = "VMWare"
        level = "100%"

        [[params.skills.list]]
        skill = "SentinelOne"
        level = "100%"

        [[params.skills.list]]
        skill = "Audit & Compliance"
        level = "100%"

        [[params.skills.list]]
        skill = "Proofpoint"
        level = "100%"

        [[params.skills.list]]
        skill = "Tenable"
        level = "100%"

        [[params.skills.list]]
        skill = "Graylog"
        level = "100%"

        [[params.skills.list]]
        skill = "KnowBe4"
        level = "100%"

        [[params.skills.list]]
        skill = "PCI Compliance"
        level = "100%"

        [[params.skills.list]]
        skill = "Exchange"
        level = "100%"

        [[params.skills.list]]
        skill = "VPN"
        level = "100%"

        [[params.skills.list]]
        skill = "Duo"
        level = "100%"

        [[params.skills.list]]
        skill = "Project Management"
        level = "100%"

        [[params.skills.list]]
        skill = "Budget Administration"
        level = "100%"

        [[params.skills.list]]
        skill = "SolarWinds"
        level = "100%"

        [[params.skills.list]]
        skill = "ManageEngine"
        level = "100%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Grant Joseph"
